### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Comment by a1346054** [comment]
Rebased to fix merge conflicts.

**Comment by mviereck** [comment]
Thank you for your contribution!
Especially spell checks are quite appreciated.
Sorry for my late response!

At some points you have added `""`, at other points you have removed them? Why did you remove some of them?

Trimming whitespace does not add value but adds a lot of lines I have to check.

My wish:
Could you change the contribution to:
 - fix spelling
 - adding `""`

but:
 - no whitepsace removal
 - no `""` removal

Than I would happily merge your PR.

**Comment by a1346054** [comment]
Thank you for the review comments.

I rebased on latest master to fix merge conflicts and dropped the commits that remove trailing whitespace from x11docker and x11docker-gui. It is always possible to remove all trailing whitespace at a later time if you wish to do so yourself (and set things up so that no new trailing whitespace is introduced).

Regarding the `""` quotes, I added them where they are strictly necessary to fix possible problems (and the associated shellcheck warnings), and removed them where they are harmless though superfluous (and often misleading). I can still rework that if you wish.

**Comment by mviereck** [comment]
Thank you.
Currently I'd like to merge the three commits titled with "fix spelling", but not the others.

> Regarding the "" quotes, I added them where they are strictly necessary to fix possible problems (and the associated shellcheck warnings), and removed them where they are harmless though superfluous (and often misleading). I can still rework that if you wish.

A commit that only adds quotes but removes none would be appreciated.

Changing `[ "$Var" ]` to `[ -n "$Var" ]` is possible but needless. It appears very often in x11docker.

**Comment by a1346054** [comment]
I'll create a separate PR that only contains the spelling fixes, and rework this PR to implement the review comments.

I generally don't like seeing `[ "$Var" ]` because a lot of people are confused that this gets executed:

```shell
a=false
if [ "$a" ]; then
    echo "This gets executed"
fi

b=0
if [ "$b" ]; then
    echo "This gets executed as well"
fi
```

**Comment by a1346054** [comment]
I applied the suggestions in the review comments and will fix the merge conflicts once #386 is merged.

**Comment by a1346054** [comment]
Rebased on master now that #386 was merged.

**Comment by mviereck** [comment]
Thank you very much!

**Pull request merged**
